# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-shield
  description: This component is responsible for enabling AWS Shield Advanced Protection for the following resources:  Application Load Balancers (ALBs), CloudFront Distributions, Elastic IPs, Route53 Hosted Zones
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component

